# Generated by Django 4.2.6 on 2023-10-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GetConsultationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('button_text', models.CharField(max_length=256)),
                ('button_link', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MainSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('button_text', models.CharField(max_length=256)),
                ('button_link', models.CharField(max_length=256)),
                ('number1', models.CharField(max_length=256)),
                ('number1_text', models.CharField(max_length=256)),
                ('number2', models.CharField(max_length=256)),
                ('number2_text', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='OffersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('process1', models.CharField(max_length=256)),
                ('process2', models.CharField(max_length=256)),
                ('process3', models.CharField(max_length=256)),
                ('button_text', models.CharField(max_length=256)),
                ('button_link', models.CharField(max_length=256)),
                ('background_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='VideSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('background_image', models.ImageField(upload_to='')),
                ('video_image', models.ImageField(upload_to='')),
                ('video_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='WhySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
