# Generated by Django 4.2.6 on 2023-10-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0002_advantagesection_feedbacksection_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideSection',
            new_name='VideoSection',
        ),
        migrations.AddField(
            model_name='mainsection',
            name='background_image',
            field=models.ImageField(default='1', upload_to=''),
            preserve_default=False,
        ),
    ]
