# Generated by Django 4.2.6 on 2023-10-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0003_rename_videsection_videosection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsection',
            name='title1',
            field=models.TextField(),
        ),
    ]
