# Generated by Django 4.2.6 on 2023-10-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0005_rename_title1_mainsection_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getconsultationsection',
            name='title',
            field=models.TextField(),
        ),
    ]
