# Generated by Django 4.2.6 on 2023-10-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0006_alter_getconsultationsection_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortingSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_section_active', models.BooleanField(default=True)),
                ('main_section_sort', models.IntegerField()),
                ('youtube_video_active', models.BooleanField(default=True)),
                ('youtube_video_sort', models.IntegerField()),
                ('why_active', models.BooleanField(default=True)),
                ('why_sort', models.IntegerField()),
                ('advantages_active', models.BooleanField(default=True)),
                ('advantages_sort', models.IntegerField()),
                ('processes_active', models.BooleanField(default=True)),
                ('processes_sort', models.IntegerField()),
                ('get_consultation_active', models.BooleanField(default=True)),
                ('get_consultation_sort', models.IntegerField()),
                ('faq_active', models.BooleanField(default=True)),
                ('faq_sort', models.IntegerField()),
                ('offers_active', models.BooleanField(default=True)),
                ('offers_sort', models.IntegerField()),
                ('feedbacks_active', models.BooleanField(default=True)),
                ('feedbacks_sort', models.IntegerField()),
            ],
        ),
    ]
