# Generated by Django 4.2.6 on 2023-12-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0010_remove_mainsection_number1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processessection',
            old_name='button_link',
            new_name='process1_text',
        ),
        migrations.RenameField(
            model_name='processessection',
            old_name='button_text',
            new_name='process1_title',
        ),
        migrations.RenameField(
            model_name='processessection',
            old_name='process1',
            new_name='process2_text',
        ),
        migrations.RenameField(
            model_name='processessection',
            old_name='process2',
            new_name='process2_title',
        ),
        migrations.RenameField(
            model_name='processessection',
            old_name='process3',
            new_name='process3_text',
        ),
        migrations.RenameField(
            model_name='processessection',
            old_name='process4',
            new_name='process3_title',
        ),
        migrations.RenameField(
            model_name='processessection',
            old_name='process5',
            new_name='process4_text',
        ),
        migrations.RemoveField(
            model_name='processessection',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='processessection',
            name='process5_icon',
        ),
        migrations.AddField(
            model_name='processessection',
            name='process4_title',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
    ]
