# Generated by Django 4.2.6 on 2023-12-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0011_rename_button_link_processessection_process1_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeliriHesablaBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('background_image', models.ImageField(upload_to='')),
                ('button_text', models.CharField(max_length=256)),
                ('button_link', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='VideoSection',
        ),
    ]
