# Generated by Django 4.2.6 on 2023-12-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0012_gelirihesablabanner_delete_videosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suallar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
            ],
        ),
    ]
