# Generated by Django 4.2.6 on 2023-12-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0014_smartinvest'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiyeSecirler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('title1', models.CharField(max_length=256)),
                ('text1', models.TextField()),
                ('title2', models.CharField(max_length=256)),
                ('text2', models.TextField()),
                ('title3', models.CharField(max_length=256)),
                ('text3', models.TextField()),
                ('title4', models.CharField(max_length=256)),
                ('text4', models.TextField()),
            ],
        ),
    ]
