# Generated by Django 4.2.6 on 2023-12-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0017_muzakireedek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punktlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punktlar', to='statik.muzakireedek')),
            ],
        ),
    ]
