# Generated by Django 4.2.6 on 2023-12-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0018_punktlar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacksection',
            options={'verbose_name': 'Müştəri Geribildirim Bölməsi', 'verbose_name_plural': 'Müştəri Geribildirim Bölməsi'},
        ),
        migrations.AlterModelOptions(
            name='formsection',
            options={'verbose_name': 'Form Bölməsi', 'verbose_name_plural': 'Form Bölməsi'},
        ),
        migrations.AlterModelOptions(
            name='gelirihesablabanner',
            options={'verbose_name': 'Gəliri Hesablə Banneri', 'verbose_name_plural': 'Gəliri Hesablə Banneri'},
        ),
        migrations.AlterModelOptions(
            name='mainsection',
            options={'verbose_name': 'Əsas Bölmə (1-ci bölmə)', 'verbose_name_plural': 'Əsas Bölmə (1-ci bölmə)'},
        ),
        migrations.AlterModelOptions(
            name='muzakireedek',
            options={'verbose_name': 'Calendly Bölməsi', 'verbose_name_plural': 'Calendly Bölməsi'},
        ),
        migrations.AlterModelOptions(
            name='niyesecirler',
            options={'verbose_name': 'Niyə Bizi Seçirlər Punkt', 'verbose_name_plural': 'Niyə Bizi Seçirlər Punktlar'},
        ),
        migrations.AlterModelOptions(
            name='offerssection',
            options={'verbose_name': 'Evlər, Villalar Bölməsi', 'verbose_name_plural': 'Evlər, Villalar Bölməsi'},
        ),
        migrations.AlterModelOptions(
            name='processessection',
            options={'verbose_name': 'Proseslər Bölməsi', 'verbose_name_plural': 'Proseslər Bölməsi'},
        ),
        migrations.AlterModelOptions(
            name='smartinvest',
            options={'verbose_name': 'Niyə Smart İnvest Bölməsi', 'verbose_name_plural': 'Niyə Smart İnvest Bölməsi'},
        ),
        migrations.AlterModelOptions(
            name='suallar',
            options={'verbose_name': 'Banner üzərindəki sual', 'verbose_name_plural': 'Banner üzərindəki suallar'},
        ),
        migrations.AlterModelOptions(
            name='whysection',
            options={'verbose_name': 'Komanda Bölməsi', 'verbose_name_plural': 'Komanda Bölməsi'},
        ),
    ]
