# Generated by Django 4.2.6 on 2024-01-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0020_alter_feedbacksection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerssection',
            name='form_button_text',
            field=models.CharField(default='Məni siyahıya əlavə edin', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerssection',
            name='form_button_url',
            field=models.CharField(default='/', max_length=256),
            preserve_default=False,
        ),
    ]
