# Generated by Django 4.2.6 on 2024-01-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0021_offerssection_form_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerssection',
            name='form_text',
            field=models.CharField(default='Əlaqə məlumatlarınızı buradan qeyd edin, yeni yatırım fürsətlərini sizə dərhal xəbər verək!', max_length=256),
            preserve_default=False,
        ),
    ]
