# Generated by Django 4.2.6 on 2024-01-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0022_offerssection_form_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsection',
            name='text3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
