# Generated by Django 4.2.6 on 2024-01-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0023_mainsection_text3'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Slider Bölmə',
                'verbose_name_plural': '            Slider Bölmə',
            },
        ),
    ]
