# Generated by Django 4.2.6 on 2024-01-10 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0024_slidersection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainsection',
            options={'verbose_name': 'Əsas Bölmə (1-ci bölmə)', 'verbose_name_plural': '             Əsas Bölmə (1-ci bölmə)'},
        ),
    ]
