# Generated by Django 4.2.6 on 2024-01-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0025_alter_mainsection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsection',
            name='background_image',
            field=models.FileField(upload_to=''),
        ),
    ]
