# Generated by Django 4.2.6 on 2024-01-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0026_alter_mainsection_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Statik səhifələr',
                'verbose_name_plural': 'Statik səhifələr',
            },
        ),
    ]
