# Generated by Django 4.2.6 on 2024-01-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0027_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerssection',
            name='title2',
            field=models.CharField(default='Digər təklilərə bax', max_length=256, verbose_name='Offer səhifəsində başlıq'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerssection',
            name='title3',
            field=models.CharField(default='İstədiyin evl tap', max_length=256, verbose_name='Offer səhifəsində alt başlıq'),
            preserve_default=False,
        ),
    ]
