# Generated by Django 4.2.6 on 2024-02-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0028_offerssection_title2_offerssection_title3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('sub_title', models.CharField(max_length=256)),
                ('success_text', models.CharField(max_length=256)),
                ('button_text', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Form Vebinara Yazıl',
                'verbose_name_plural': 'Form Vebinara Yazıl',
            },
        ),
        migrations.CreateModel(
            name='Form2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_text', models.CharField(max_length=256)),
                ('button_text', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Form Listing',
                'verbose_name_plural': 'Form Listing',
            },
        ),
        migrations.CreateModel(
            name='Form3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_text', models.CharField(max_length=256)),
                ('button_text', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Form Özün tapmısan',
                'verbose_name_plural': 'Form Özün tapmısan',
            },
        ),
        migrations.CreateModel(
            name='Form4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('sub_title', models.CharField(max_length=256)),
                ('success_text', models.CharField(max_length=256)),
                ('button_text', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Form Property Viewing',
                'verbose_name_plural': 'Form Property Viewing',
            },
        ),
    ]
