# Generated by Django 4.2.6 on 2024-02-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0029_form1_form2_form3_form4'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form1',
            options={'verbose_name': 'Form Vebinara Yazıl', 'verbose_name_plural': 'Form - Vebinara Yazıl'},
        ),
        migrations.AlterModelOptions(
            name='form2',
            options={'verbose_name': 'Form Listing', 'verbose_name_plural': 'Form - Listing'},
        ),
        migrations.AlterModelOptions(
            name='form3',
            options={'verbose_name': 'Form Özün tapmısan', 'verbose_name_plural': 'Form - Özün tapmısan'},
        ),
        migrations.AlterModelOptions(
            name='form4',
            options={'verbose_name': 'Form Property Viewing', 'verbose_name_plural': 'Form - Property Viewing'},
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name': ' Statik səhifələr', 'verbose_name_plural': ' Statik səhifələr'},
        ),
        migrations.AddField(
            model_name='form1',
            name='text1',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form1',
            name='text2',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
