# Generated by Django 4.2.6 on 2024-02-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0030_alter_form1_options_alter_form2_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('button_text', models.CharField(max_length=256)),
                ('dateime', models.CharField(max_length=256)),
                ('user1_image', models.ImageField(upload_to='')),
                ('user1_name', models.CharField(max_length=256)),
                ('user1_profession', models.CharField(max_length=256)),
                ('user2_image', models.ImageField(upload_to='')),
                ('user2_name', models.CharField(max_length=256)),
                ('user2_profession', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Coffee Section',
                'verbose_name_plural': 'Coffee Section',
            },
        ),
    ]
