# Generated by Django 4.2.6 on 2023-10-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=256)),
                ('meta_description', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('copyright', models.CharField(max_length=256)),
                ('logo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Ümumi Məlumatlar',
                'verbose_name_plural': 'Ümumi Məlumatlar',
            },
        ),
    ]
