# Generated by Django 4.2.6 on 2023-10-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=256)),
                ('icon', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Sosial Media Hesabı',
                'verbose_name_plural': 'Sosial Media Hesabları',
            },
        ),
    ]
