# Generated by Django 4.2.6 on 2023-10-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_advisorcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
