# Generated by Django 4.2.6 on 2023-10-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_general_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Why Alanya',
                'verbose_name_plural': 'Why Alanya',
            },
        ),
    ]
