# Generated by Django 4.2.6 on 2023-10-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_why'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='')),
                ('text', models.CharField(max_length=256)),
                ('icon', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Tablar',
                'verbose_name_plural': 'Tablar',
            },
        ),
    ]
