# Generated by Django 4.2.6 on 2023-10-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tablar'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='telegram_link',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='general',
            name='whatsapp_link',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
    ]
