# Generated by Django 4.2.6 on 2023-10-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='home_popup_video',
            field=models.FileField(default='1', upload_to=''),
            preserve_default=False,
        ),
    ]
