# Generated by Django 4.2.6 on 2023-10-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_general_home_popup_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='')),
                ('full_name', models.CharField(max_length=256)),
                ('position', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('background_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
