# Generated by Django 4.2.6 on 2023-10-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvisorContact',
        ),
        migrations.AlterField(
            model_name='tablar',
            name='text',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tablar',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
