# Generated by Django 4.2.6 on 2023-12-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_advisorcontact_alter_tablar_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='surname',
            new_name='email',
        ),
    ]
