# Generated by Django 4.2.6 on 2023-12-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_surname_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=256)),
                ('icon', models.FileField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
    ]
