# Generated by Django 4.2.6 on 2023-12-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='color',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
    ]
