# Generated by Django 4.2.6 on 2023-12-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_general_countdown_enddate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Waitlist',
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('sort',), 'verbose_name': 'FAQ Sual', 'verbose_name_plural': 'FAQ Suallar'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Niyə? Səbəblər', 'verbose_name_plural': 'Niyə? Səbəblər'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Müştəri Geri Bildirim', 'verbose_name_plural': 'Müştəri Geri Bildirimləri'},
        ),
        migrations.AlterModelOptions(
            name='general',
            options={'verbose_name': 'Ümumi Sayt Məlumatlar', 'verbose_name_plural': 'Ümumi Sayt Məlumatlar'},
        ),
        migrations.AlterModelOptions(
            name='why',
            options={'verbose_name': 'Komanda üzvü', 'verbose_name_plural': 'Komanda'},
        ),
    ]
