# Generated by Django 4.2.6 on 2023-12-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_contact_delete_waitlist_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Kalkulyator Parametrlər',
                'verbose_name_plural': 'Kalkulyator Parametrlər',
            },
        ),
    ]
