# Generated by Django 4.2.6 on 2023-12-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_calculator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('script', models.TextField()),
            ],
            options={
                'verbose_name': "Body'ə əlavə olunan scriptlər",
                'verbose_name_plural': "Body'ə əlavə olunan scriptlər",
            },
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('script', models.TextField()),
            ],
            options={
                'verbose_name': "Head'ə əlavə olunan scriptlər",
                'verbose_name_plural': "Head'ə əlavə olunan scriptlər",
            },
        ),
    ]
