# Generated by Django 4.2.6 on 2023-12-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_body_options_alter_head_options_body_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body',
            options={'verbose_name': '  JS Script', 'verbose_name_plural': '  JS Scriptlər'},
        ),
        migrations.AlterField(
            model_name='body',
            name='location',
            field=models.CharField(choices=[('H', 'Script in between HEAD tags'), ('T', 'After <body> tag opened'), ('B', 'Before </body> tag closed')], default='T', max_length=1),
        ),
    ]
