# Generated by Django 4.2.6 on 2023-12-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_body_options_alter_body_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leverage_tr', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Leverage TR')),
                ('leverage_az', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Leverage AZ')),
                ('loan_interest_rate_tr', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Loan Interest Rate TR')),
                ('loan_interest_rate_az', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Loan Interest Rate AZ')),
                ('appraisal_rate_tr', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Appraisal Rate TR')),
                ('appraisal_rate_az', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Appraisal Rate AZ')),
                ('rental_growth_tr', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Rental Growth TR')),
                ('rental_growth_az', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Rental Growth AZ')),
                ('interest_rate_tr', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Interest Rate TR')),
                ('interest_rate_az', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Interest Rate AZ')),
                ('diger_xercler_tr', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Digər Xərclər TR')),
                ('diger_xercler_az', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Digər Xərclər AZ')),
                ('heyat_sigortasi_tr', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Həyat Siğortası TR')),
                ('heyat_sigortasi_az', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Həyat Siğortası AZ')),
                ('kiraye_kofisent_tr', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Kirayə Gəliri Kofisenti TR')),
                ('kiraye_kofisent_az', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Kirayə Gəliri Kofisenti AZ')),
            ],
            options={
                'verbose_name': 'Kalkulyator Parametrlər',
                'verbose_name_plural': 'Kalkulyator Parametrlər',
            },
        ),
        migrations.DeleteModel(
            name='Calculator',
        ),
    ]
