# Generated by Django 4.2.6 on 2023-12-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_parametr_delete_calculator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametr',
            options={'verbose_name': 'Kalkulyator Parametrləri', 'verbose_name_plural': 'Kalkulyator Parametrləri'},
        ),
        migrations.AlterField(
            model_name='parametr',
            name='diger_xercler_az',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Digər Xərclər AZ'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='diger_xercler_tr',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Digər Xərclər TR'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='heyat_sigortasi_az',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Həyat Siğortası AZ'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='heyat_sigortasi_tr',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Həyat Siğortası TR'),
        ),
    ]
