# Generated by Django 4.2.6 on 2023-12-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_parametr_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametr',
            name='interest_rate_az',
        ),
        migrations.RemoveField(
            model_name='parametr',
            name='interest_rate_tr',
        ),
        migrations.AddField(
            model_name='parametr',
            name='interest_rate_bank',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=8, verbose_name='Bank Interest Rate AZ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parametr',
            name='leverage_az',
            field=models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Leverage Percent AZ'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='leverage_tr',
            field=models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Leverage Percent TR'),
        ),
    ]
