# Generated by Django 4.2.6 on 2023-12-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_parametr_interest_rate_az_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametr',
            name='appraisal_rate_az',
            field=models.FloatField(verbose_name='Appraisal Rate AZ'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='appraisal_rate_tr',
            field=models.FloatField(verbose_name='Appraisal Rate TR'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='diger_xercler_az',
            field=models.FloatField(verbose_name='Digər Xərclər AZ'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='diger_xercler_tr',
            field=models.FloatField(verbose_name='Digər Xərclər TR'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='heyat_sigortasi_az',
            field=models.FloatField(verbose_name='Həyat Siğortası AZ'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='heyat_sigortasi_tr',
            field=models.FloatField(verbose_name='Həyat Siğortası TR'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='interest_rate_bank',
            field=models.FloatField(verbose_name='Bank Interest Rate AZ'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='kiraye_kofisent_az',
            field=models.FloatField(verbose_name='Kirayə Gəliri Kofisenti AZ'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='kiraye_kofisent_tr',
            field=models.FloatField(verbose_name='Kirayə Gəliri Kofisenti TR'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='leverage_az',
            field=models.FloatField(verbose_name='Leverage Percent AZ'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='leverage_tr',
            field=models.FloatField(verbose_name='Leverage Percent TR'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='loan_interest_rate_az',
            field=models.FloatField(verbose_name='Loan Interest Rate AZ'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='loan_interest_rate_tr',
            field=models.FloatField(verbose_name='Loan Interest Rate TR'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='rental_growth_az',
            field=models.FloatField(verbose_name='Rental Growth AZ'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='rental_growth_tr',
            field=models.FloatField(verbose_name='Rental Growth TR'),
        ),
    ]
