# Generated by Django 4.2.6 on 2024-01-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_parametr_appraisal_rate_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='why',
            name='position',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
    ]
