# Generated by Django 4.2.6 on 2024-01-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_why_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='logo_white',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
