# Generated by Django 4.2.6 on 2024-01-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_general_countdown_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
