# Generated by Django 4.2.6 on 2024-01-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_slider_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendlyScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('script', models.TextField()),
            ],
        ),
    ]
