# Generated by Django 4.2.6 on 2024-01-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_slider_image_link_alter_slider_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='black_layer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='button_color',
            field=models.CharField(choices=[('B', 'Black'), ('W', 'White')], default='W', max_length=1),
        ),
    ]
