# Generated by Django 4.2.6 on 2024-01-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_slider_button_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='button_color',
            field=models.CharField(choices=[('B', 'black'), ('W', 'white')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='slider',
            name='button_text_color',
            field=models.CharField(choices=[('B', 'black'), ('W', 'white')], default='B', max_length=1),
        ),
    ]
