# Generated by Django 4.2.6 on 2024-01-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_slider_black_layer_slider_black_layer_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='black_layer_css',
            field=models.CharField(blank=True, default='background: linear-gradient(90deg, #000 33.33%, rgba(0, 0, 0, 0.00) 99.89%);', max_length=256, null=True),
        ),
    ]
