# Generated by Django 4.2.6 on 2024-02-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_slider_mobile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='')),
                ('full_name', models.CharField(max_length=256)),
                ('position', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('background_image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Müştəri Geri Bildirim',
                'verbose_name_plural': 'Müştəri Geri Bildirimləri',
            },
        ),
        migrations.CreateModel(
            name='SliderTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=256)),
                ('mobile_title', models.CharField(blank=True, max_length=256, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=256, null=True)),
                ('button_url', models.CharField(blank=True, max_length=256, null=True)),
                ('button_color', models.CharField(choices=[('B', 'black'), ('W', 'white')], default='W', max_length=1)),
                ('button_text_color', models.CharField(choices=[('B', 'black'), ('W', 'white')], default='B', max_length=1)),
                ('image_link', models.CharField(blank=True, max_length=256, null=True)),
                ('sorting', models.IntegerField(default=1)),
                ('black_layer_css', models.CharField(blank=True, default='background: linear-gradient(90deg, #000 33.33%, rgba(0, 0, 0, 0.00) 99.89%)', max_length=256, null=True)),
                ('black_layer_css_mobile', models.CharField(blank=True, default='background: linear-gradient(180deg, #000 33.33%, rgba(0, 0, 0, 0.00) 99.89%)', max_length=256, null=True)),
            ],
            options={
                'ordering': ('sorting',),
            },
        ),
    ]
