# Generated by Django 4.2.6 on 2024-02-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_faqtr_featuretr_generaltr_whytr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqtr',
            options={'ordering': ('sort',), 'verbose_name': 'FAQ Sual', 'verbose_name_plural': 'Tr FAQ Suallar'},
        ),
        migrations.AlterModelOptions(
            name='feedbacktr',
            options={'verbose_name': 'Tr Müştəri Geri Bildirim', 'verbose_name_plural': 'Tr Müştəri Geri Bildirimləri'},
        ),
        migrations.AlterModelOptions(
            name='slidertr',
            options={'ordering': ('sorting',), 'verbose_name': 'Tr Slider', 'verbose_name_plural': 'Tr Slider'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='faqru',
            name='answer',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='faqtr',
            name='answer',
            field=models.CharField(max_length=512),
        ),
    ]
