# Generated by Django 4.2.6 on 2024-03-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_vebinarform'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenzilForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('placeholder', models.CharField(max_length=256)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Menzil Form Dynamic ',
                'verbose_name_plural': 'Menzil Form Dynamic ',
                'ordering': ('sort',),
            },
        ),
    ]
