# Generated by Django 4.2.6 on 2024-03-08 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_menzilform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menzilform',
            options={'ordering': ('sort',), 'verbose_name': 'Dynamic Menzil Form  ', 'verbose_name_plural': 'Dynamic Menzil Form  '},
        ),
        migrations.AlterModelOptions(
            name='vebinarform',
            options={'ordering': ('sort',), 'verbose_name': 'Dynamic Vebinar Form', 'verbose_name_plural': 'Dynamic Vebinar Form'},
        ),
    ]
