# Generated by Django 4.2.6 on 2024-03-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_menzilform_options_alter_vebinarform_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenzilFormRU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('placeholder', models.CharField(max_length=256)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dynamic Menzil Form RU',
                'verbose_name_plural': 'Dynamic Menzil Form RU',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='MenzilFormTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('placeholder', models.CharField(max_length=256)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dynamic Menzil Form TR',
                'verbose_name_plural': 'Dynamic Menzil Form TR',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='VebinarFormRU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('placeholder', models.CharField(max_length=256)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dynamic Vebinar Form RU',
                'verbose_name_plural': 'Dynamic Vebinar Form RU',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='VebinarFormTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('placeholder', models.CharField(max_length=256)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dynamic Vebinar Form TR',
                'verbose_name_plural': 'Dynamic Vebinar Form TR',
                'ordering': ('sort',),
            },
        ),
    ]
