# Generated by Django 4.2.6 on 2023-10-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='address',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='bath',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='bed',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='1', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='square',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
    ]
