# Generated by Django 4.2.6 on 2023-10-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_offer_address_offer_bath_offer_bed_offer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='type',
            field=models.CharField(choices=[('V', 'Villa'), ('A', 'Apartment')], default='V', max_length=1),
        ),
    ]
