# Generated by Django 4.2.6 on 2023-10-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_offer_distance_to_airport_offer_distance_to_beach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='balcon',
            field=models.CharField(default='2', max_length=256),
        ),
        migrations.AddField(
            model_name='offer',
            name='chambres',
            field=models.CharField(default='2', max_length=256),
        ),
        migrations.AddField(
            model_name='offer',
            name='heating_system',
            field=models.CharField(default='Floor', max_length=256),
        ),
        migrations.AddField(
            model_name='offer',
            name='indoor_parking',
            field=models.CharField(default='1', max_length=256),
        ),
        migrations.AddField(
            model_name='offer',
            name='rooms',
            field=models.CharField(default='2', max_length=256),
        ),
        migrations.AddField(
            model_name='offer',
            name='sanitaires',
            field=models.CharField(default='2', max_length=256),
        ),
        migrations.AddField(
            model_name='offer',
            name='wc_qty',
            field=models.CharField(default='2', max_length=256),
        ),
    ]
