# Generated by Django 4.2.6 on 2023-10-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_offer_balcon_offer_chambres_offer_heating_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(default="Coracesium City is located in Oba, Alanya, the charming and beautiful holiday resort of Antalya. In the project, you will live every moment of your life as if you were on holiday. Coracesium City is built on an area of \u200b\u200b804.13 square meters and consists of 20 units. In the project, you can enjoy tranquility and peaceful life with your loved ones. There are apartment options in the project that appeal to all lifestyles. The project offers 1-bedroom, 2-bedroom, 3-bedroom, and 4-bedroom apartment options and the sizes of the apartments vary from 45 square meters to 162 square meters. In the project, there are privileged social opportunities for you to experience happiness and summer to the fullest. These include an indoor swimming pool and a children's playground. The barbecue area is also included in the project for you to spend a nice weekend with your loved ones. For every moment you want to relax, there is a sauna in Coracesium City. In addition, a fitness center with state-of-the-art equipment for a healthy and sporty life is also included in the project. Coracesium City is the place you should choose for a peaceful and pleasant life in Alanya. Do not miss the exclusive opportunities of Coracesium City."),
            preserve_default=False,
        ),
    ]
