# Generated by Django 4.2.6 on 2023-12-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_offer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='ilkin_mebleg',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='maks_ayliq_kiraye',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='on_il_sonraki_qiymet',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='real_bazar_qiymeti',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='umumi_mebleg',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='umumi_net_gelir',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
