# Generated by Django 4.2.6 on 2023-12-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_offer_ilkin_mebleg_offer_maks_ayliq_kiraye_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Ev, Villa', 'verbose_name_plural': 'Evlər, Villalar'},
        ),
    ]
