# Generated by Django 4.2.6 on 2024-01-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='emlakın_deyeri',
            field=models.FloatField(default=0, verbose_name='Əmlakın 10 İl Sonrakı Dəyəei'),
        ),
        migrations.AddField(
            model_name='offer',
            name='ilkin_kapital',
            field=models.FloatField(default=0, verbose_name='İlkin kapital'),
        ),
        migrations.AddField(
            model_name='offer',
            name='kiraye_geliri',
            field=models.FloatField(default=0, verbose_name='Ortalama Kirayə Gəliri'),
        ),
        migrations.AddField(
            model_name='offer',
            name='kirayeci',
            field=models.CharField(default=1, max_length=256, verbose_name='Kirayəçi Yerləşdirmə'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='net_qazanc',
            field=models.FloatField(default=0, verbose_name='Net Qazanc'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.FloatField(default=0, verbose_name='Əmlakın dəyəri'),
        ),
    ]
