# Generated by Django 4.2.6 on 2024-01-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_offer_emlakın_deyeri_offer_ilkin_kapital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.FloatField(default=0, verbose_name='Əmlakın Indiki Dəyəri'),
        ),
    ]
