# Generated by Django 4.2.6 on 2024-01-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_alter_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='emlakın_deyeri',
            field=models.FloatField(blank=True, null=True, verbose_name='Əmlakın 10 İl Sonrakı Dəyəei'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='ilkin_kapital',
            field=models.FloatField(blank=True, null=True, verbose_name='İlkin kapital'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='kiraye_geliri',
            field=models.FloatField(blank=True, null=True, verbose_name='Ortalama Kirayə Gəliri'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='net_qazanc',
            field=models.FloatField(blank=True, null=True, verbose_name='Net Qazanc'),
        ),
    ]
