# Generated by Django 4.2.6 on 2024-01-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0013_alter_offer_emlakın_deyeri_alter_offer_ilkin_kapital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='emlakın_deyeri',
            field=models.IntegerField(blank=True, null=True, verbose_name='Əmlakın 10 İl Sonrakı Dəyəri'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='ilkin_kapital',
            field=models.IntegerField(blank=True, null=True, verbose_name='İlkin kapital'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='kiraye_geliri',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ortalama Kirayə Gəliri'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='net_qazanc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Net Qazanc'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Əmlakın Indiki Dəyəri'),
        ),
    ]
