# Generated by Django 4.2.6 on 2024-01-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0014_alter_offer_emlakın_deyeri_alter_offer_ilkin_kapital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(choices=[('V', 'Villa'), ('M', 'Mənzil'), ('E', 'Ev'), ('T', 'Torpaq'), ('Q', 'Qeyri-yaşayış'), ('B', 'Bina')], default='V', max_length=1),
        ),
    ]
