# Generated by Django 4.2.6 on 2024-01-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0015_alter_offer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(choices=[('V', 'Villa'), ('A', 'Mənzil'), ('E', 'Ev'), ('T', 'Torpaq'), ('Q', 'Qeyri-yaşayış'), ('B', 'Bina')], default='V', max_length=1),
        ),
    ]
