# Generated by Django 4.2.6 on 2024-02-15 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0018_offer_is_sold_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferRU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sold_out', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0, verbose_name='Əmlakın Indiki Dəyəri')),
                ('ilkin_kapital', models.IntegerField(blank=True, null=True, verbose_name='İlkin kapital')),
                ('kiraye_geliri', models.IntegerField(blank=True, null=True, verbose_name='Ortalama Kirayə Gəliri')),
                ('emlakın_deyeri', models.IntegerField(blank=True, null=True, verbose_name='Əmlakın 10 İl Sonrakı Dəyəri')),
                ('net_qazanc', models.IntegerField(blank=True, null=True, verbose_name='Net Qazanc')),
                ('kirayeci', models.CharField(max_length=256, verbose_name='Kirayəçi Yerləşdirmə')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('project_status', models.CharField(max_length=256)),
                ('year_built', models.CharField(max_length=256)),
                ('distance_to_beach', models.CharField(max_length=256)),
                ('distance_to_center', models.CharField(max_length=256)),
                ('distance_to_airport', models.CharField(max_length=256)),
                ('state_guaranteed', models.CharField(max_length=256)),
                ('sea_view', models.CharField(max_length=256)),
                ('installment', models.CharField(max_length=256)),
                ('suitable_for_citizenship', models.CharField(max_length=256)),
                ('bed', models.CharField(max_length=256)),
                ('bath', models.CharField(max_length=256)),
                ('square', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('V', 'Villa'), ('A', 'Mənzil'), ('E', 'Ev'), ('T', 'Torpaq'), ('Q', 'Qeyri-yaşayış'), ('N', 'Bina')], default='V', max_length=1)),
                ('image', models.ImageField(upload_to='')),
                ('sanitaires', models.CharField(default='2', max_length=256)),
                ('balcon', models.CharField(default='2', max_length=256)),
                ('rooms', models.CharField(default='2', max_length=256)),
                ('chambres', models.CharField(default='2', max_length=256)),
                ('wc_qty', models.CharField(default='2', max_length=256)),
                ('indoor_parking', models.CharField(default='1', max_length=256)),
                ('heating_system', models.CharField(default='Floor', max_length=256)),
                ('description', models.TextField()),
                ('ilkin_mebleg', models.CharField(blank=True, max_length=256, null=True)),
                ('maks_ayliq_kiraye', models.CharField(blank=True, max_length=256, null=True)),
                ('real_bazar_qiymeti', models.CharField(blank=True, max_length=256, null=True)),
                ('umumi_mebleg', models.CharField(blank=True, max_length=256, null=True)),
                ('on_il_sonraki_qiymet', models.CharField(blank=True, max_length=256, null=True)),
                ('umumi_net_gelir', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Ev, Villa',
                'verbose_name_plural': 'Ru Evlər, Villalar',
            },
        ),
        migrations.CreateModel(
            name='ImageRU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='offer.offerru')),
            ],
        ),
    ]
