# Generated by Django 4.2.6 on 2024-02-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0020_offertr_imagetr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offertr',
            options={'verbose_name': 'Ev, Villa', 'verbose_name_plural': 'Tr Evlər, Villalar'},
        ),
    ]
