# Generated by Django 4.2.6 on 2024-03-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0021_alter_offertr_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('is_sold_out',), 'verbose_name': 'Ev, Villa', 'verbose_name_plural': 'Evlər, Villalar'},
        ),
    ]
