# Generated by Django 5.1 on 2024-09-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0022_alter_offer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='mertebe',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mərtəbə'),
        ),
    ]
