# Generated by Django 4.2.6 on 2023-12-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Əlaqə Formu Müraciət',
                'verbose_name_plural': 'Əlaqə Formu Müraciətlər',
            },
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Gözləmədə Olan',
                'verbose_name_plural': 'Gözləmədə Olanlar',
            },
        ),
    ]
