# Generated by Django 3.2 on 2024-01-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vebinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('prefix', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Vebinar Müraciət',
                'verbose_name_plural': 'Vebinar Müraciətlər',
            },
        ),
    ]
