# Generated by Django 3.2 on 2024-01-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_vebinar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vebinar',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='vebinar',
            name='last_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
