# Generated by Django 4.2.6 on 2024-03-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20240130_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='vebinar',
            name='dynamic_fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
